# Loading session

In [1]:
import importlib, Saxo
importlib.reload(Saxo)
from Saxo import SaxoClient
import Key as Key


client = SaxoClient(
    app_key=Key.app_key,
    app_secret=Key.app_secret,
    app_name=Key.app_name,
    redirect_uri=Key.redirect_uri
)

# Remplace ton ancien login par celui-ci :
client.smart_login()# Ton code de trading continue ici...
print(f"Solde cash : {client.get_cash()}")

📂 Jetons chargés depuis le fichier.
🔑 Token chargé et session prête.
🔄 Renouvellement du token via Refresh Token...
❌ Échec du refresh : 401 Client Error: Unauthorized for url: https://live.logonvalidation.net/token

➡️ Ouvre ton navigateur et connecte-toi (LIVE):
https://live.logonvalidation.net/authorize?response_type=code&client_id=af9b78bc2462497e9fb519f61dcb5b68&redirect_uri=http%3A%2F%2Flocalhost%3A8001%2Fcallback&state=9T-5VwTcE1_cB0hCLxlhUUXEwsE5nZ9h

⏳ En attente du code sur http://localhost:8001/callback ...

127.0.0.1 - - [12/Mar/2026 21:22:45] "GET /callback?code=5e37ff85-bc3b-4036-84de-fea472a3c714&state=9T-5VwTcE1_cB0hCLxlhUUXEwsE5nZ9h HTTP/1.1" 200 -

✔ Code OAuth reçu : 5e37ff85-bc3b-4036-84de-fea472a3c714

🎉 TOKEN LIVE OBTENU !
💾 Jetons sauvegardés localement.
✅ Session toujours active.
Solde cash : 126.52

## GETTING ACCOUNT DATA

#### Getting cash

**client.get_cash()**

return : 

- The ammount of Cash as Float

In [2]:
cash=client.get_cash()
cash

✅ Session toujours active.

126.52

#### Getting account Metadata

**client.get_accounts()**

return a dictionnaire with all account info

In [3]:
accounts = client.get_accounts()
accounts
# for a in accounts:
#     print(a["AccountKey"]+"\n",
#            a["AccountType"]+"\n",
#              a["Currency"]+"\n",
#                a["AccountId"]+"\n")

[{'AccountGroupKey': 'i0BGkBS3wECMu8OPUdKIxA==',
  'AccountGroupName': 'Saxo Banque SRD',
  'AccountId': '78800/166433EUR',
  'AccountKey': 'r5JIKMkqsHq5a-PpeifkDw==',
  'AccountSubType': 'None',
  'AccountType': 'Normal',
  'Active': True,
  'CanUseCashPositionsAsMarginCollateral': True,
  'ClientId': '21777080',
  'ClientKey': 'bEdUJ23N|C-htOc8vG6oAw==',
  'CreationDate': '2026-01-21T21:04:18.357000Z',
  'Currency': 'EUR',
  'CurrencyDecimals': 2,
  'DirectMarketAccess': False,
  'DisplayName': 'Compte-titres SRD',
  'FractionalOrderEnabled': False,
  'FractionalOrderEnabledAssetTypes': [],
  'IndividualMargining': False,
  'IsCurrencyConversionAtSettlementTime': False,
  'IsMarginTradingAllowed': True,
  'IsShareable': False,
  'IsTrialAccount': False,
  'LegalAssetTypes': ['Stock',
   'Bond',
   'Cash',
   'MutualFund',
   'Etf',
   'Etc',
   'Etn',
   'Fund',
   'Rights',
   'Warrant',
   'MiniFuture',
   'WarrantSpread',
   'WarrantKnockOut',
   'WarrantOpenEndKnockOut',
   'WarrantDoubleKnockOut',
   'CertificateUncappedCapitalProtection',
   'CertificateCappedCapitalProtected',
   'CertificateDiscount',
   'CertificateCappedOutperformance',
   'CertificateCappedBonus',
   'CertificateExpress',
   'CertificateTracker',
   'CertificateUncappedOutperformance',
   'CertificateBonus',
   'CertificateConstantLeverage',
   'SrdOnStock',
   'SrdOnEtf',
   'IpoOnStock',
   'CompanyWarrant',
   'SubscriptionOnCertificate',
   'StockIndex'],
  'ManagementType': 'Client',
  'MarginCalculationMethod': 'Default',
  'MarginLendingEnabled': 'None',
  'PortfolioBasedMarginEnabled': False,
  'Sharing': ['NoSharing'],
  'SupportsAccountValueProtectionLimit': False,
  'UseCashPositionsAsMarginCollateral': True}]

#### Getting positions

**get_positions()**

return df with :
- name
- type
- uic
- quantity
- current_price
- underlying_price
- strike
- levrage
- pnl (€)
- currency
- pnl (%)

In [4]:
res = client.get_positions()
res

✅ Session toujours active.

Empty DataFrame
Columns: []
Index: []

#### Getting Order list

**client.get_open_orders()**

return un dictionnaire avec tout plein d'info

In [25]:
ordres_actifs = client.get_open_orders_full_info()
print(f"Vous avez {len(ordres_actifs)} ordre(s) en cours.")

✅ Session toujours active.
Vous avez 1 ordre(s) en cours.

In [26]:
ordres_actifs = client.get_open_orders_full_info()
ordres_actifs

✅ Session toujours active.

[{'AccountId': '78800/166433EUR',
  'AccountKey': 'r5JIKMkqsHq5a-PpeifkDw==',
  'AdviceNote': '',
  'Amount': 2.0,
  'Ask': 2.481,
  'AssetType': 'MiniFuture',
  'Bid': 2.469,
  'BuySell': 'Buy',
  'CalculationReliability': 'Ok',
  'ClientId': '21777080',
  'ClientKey': 'bEdUJ23N|C-htOc8vG6oAw==',
  'ClientName': 'Jérémy Antoine Viot',
  'ClientNote': '',
  'CorrelationKey': '5f2d62b4-4d53-471c-be5a-8430f0a3b10b',
  'CurrentPrice': 2.481,
  'CurrentPriceDelayMinutes': 0,
  'CurrentPriceLastTraded': '1899-12-30T00:00:00.000000Z',
  'CurrentPriceType': 'Ask',
  'DistanceToMarket': 2.461,
  'Duration': {'DurationType': 'DayOrder'},
  'Exchange': {'Description': 'CATS_SAXO',
   'ExchangeId': 'CATS_SAXO',
   'IsOpen': False,
   'TimeZoneId': '4'},
  'IpoSubscriptionFee': 0.0,
  'IsExtendedHoursEnabled': False,
  'IsForceOpen': False,
  'IsMarketOpen': True,
  'MarketPrice': 2.481,
  'MarketState': 'Open',
  'MarketValue': 0.0,
  'NonTradableReason': 'None',
  'OpenOrderType': 'Limit',
  'OptionsData': {'FinancingLevel': 740.349347,
   'PutCall': 'None',
   'Ratio': 100.0,
   'StopLossLevel': 703.33188,
   'TradePerspective': 'Short'},
  'OrderAmountType': 'Quantity',
  'OrderId': '5382455430',
  'OrderRelation': 'StandAlone',
  'OrderTime': '2026-03-12T20:23:42.751198Z',
  'Price': 0.02,
  'RelatedOpenOrders': [],
  'Status': 'Working',
  'TradingStatus': 'Tradable',
  'Uic': 54287165}]

#### Getting order Short info  as a DF

**get_open_orders()**

return un df : 
- Id de l'ordre
- Uic
- AssetType
- Amount
- BuySell
- OrderPrice
- Stutus (jsp a quoi ce sert)

In [7]:
ORD=client.get_open_orders()
ORD

✅ Session toujours active.
✅ Session toujours active.

Empty DataFrame
Columns: []
Index: []

#### Getting transaction Histo

**client.get_last_trades(`n`, `uic`)**

- `n`   => The number of transac you want buddy
- `uic` => The UIC *(ID)* of the current product




return df with :
- TradeTimestamp	
- ValueDate	
- BuySell	
- ToOpenOrClose	Price	
- Quantity	
- BookedAmount	
- Currency	
- Uic	
- TradeId	
- Description

In [8]:
# 30 dernières exécutions sur ce produit (fenêtre héritée de get_last_transactions si fournie)
df = client.get_last_trades(n=30, uic=42571691)
df

✅ Session toujours active.
✅ Session toujours active.

,TradeTimestamp,ValueDate,BuySell,ToOpenOrClose,Price,Quantity,BookedAmount,Currency,Uic,TradeId,Description
0,2026-02-27 12:18:34.550000+00:00,2026-03-03,Sell,ToOpen,7.46,-1.0,7.46,EUR,42571691,6607939567,TotalEnergies Turbo Long 31.9608 Saxo
1,2026-02-25 12:49:12.067000+00:00,2026-02-27,Buy,ToOpen,7.44,1.0,-7.44,EUR,42571691,6604194576,TotalEnergies Turbo Long 31.9608 Saxo

## GET PRODUCT DATA

#### Getting current price

Obtiens le Bid et Ask en temps reel

In [9]:
info = client.info_needed_for_trading("CH1351250548")
# client.get_market_price(info["uic"], info["type"])
client.get_price_forced(info["uic"], info["type"])

✅ Session toujours active.
✅ Session toujours active.

{'Instrument': 'TotalEnergies Turbo Long 31.9608 Saxo',
 'Dernier_Cours': None,
 'Achat_Bid': None,
 'Vente_Ask': None,
 'Clôture_Précédente': 0.0,
 'Statut_Prix': None,
 'Devise': 'EUR',
 'Message': 'Marché fermé ou flux restreint'}

#### Getting a large range of data

In [12]:
import pandas as pd
all_data = []
for date in pd.date_range(start="2026-03-05", end="2026-03-06"):
    start_time = date.strftime("%Y-%m-%d") + "T09:00:00"
    end_time = date.strftime("%Y-%m-%d") + "T17:00:00"
    
    df = client.get_chart_data_range(
        uic=23255427, 
        start_time=start_time, 
        end_time=end_time, 
        asset_type="SrdOnStock",  # Ton type d’asset
        horizon=1
    )
    all_data.append(df)
full_data = pd.concat(all_data, ignore_index=True)
full_data

✅ Session toujours active.
📊 Mode: UpTo | Date: 2026-03-05T17:00:00Z | Count: 482 | Asset: SrdOnStock
✅ Session toujours active.
✓ Données récupérées pour Instrument
  Description: N/A
  Devise: N/A
  Décimales: N/A
  Délai: 0 minutes
  Intervalle: 1 minutes
  Nombre de barres: 482
  Période: 2026-03-05 08:31:00+00:00 à 2026-03-05 16:38:00+00:00
✅ Session toujours active.
📊 Mode: UpTo | Date: 2026-03-06T17:00:00Z | Count: 482 | Asset: SrdOnStock
✅ Session toujours active.
✓ Données récupérées pour Instrument
  Description: N/A
  Devise: N/A
  Décimales: N/A
  Délai: 0 minutes
  Intervalle: 1 minutes
  Nombre de barres: 482
  Période: 2026-03-06 08:33:00+00:00 à 2026-03-06 16:39:00+00:00

     Close   High  Interest    Low   Open     Volume
0    66.85  66.90       0.0  66.85  66.89     9012.0
1    66.80  66.85       0.0  66.79  66.85     6810.0
2    66.82  66.84       0.0  66.77  66.80     6764.0
3    66.79  66.82       0.0  66.78  66.81     7311.0
4    66.73  66.79       0.0  66.72  66.79     5280.0
..     ...    ...       ...    ...    ...        ...
959  68.00  68.00       0.0  68.00  68.00  2739145.0
960  68.00  68.00       0.0  68.00  68.00     4501.0
961  68.00  68.00       0.0  68.00  68.00    30701.0
962  68.00  68.00       0.0  68.00  68.00    17415.0
963  68.00  68.00       0.0  68.00  68.00    12402.0

[964 rows x 6 columns]

#### Get Hisorical prices

get_chart_data(`uic`,`asset_type`,`horizon`,`count`,`mode`,`time`)


 - Universal Instrument Code (ex: 21 pour EUR/USD)
 - asset_type (str): Type d'actif (FxSpot, Stock, etc.)
 - horizon (int): Intervalle en minutes (1, 5, 15, 60, 1440=daily, etc.)
 - count (int): Nombre de barres à récupérer (max 1200)
 - mode (str): 'From' ou 'UpTo' - si spécifié, time doit aussi être spécifié
 - time (str): Date/heure ISO format (ex: '2026-02-13T00:00:00Z')

return un df

In [13]:

info = client.info_needed_for_trading("CH1351250548")


df=client.get_chart_data(info["uic"], info["type"], horizon=1440, count=1200, mode=None, time=None)
df

✅ Session toujours active.
✅ Session toujours active.
✓ Données récupérées pour Instrument
  Description: N/A
  Devise: N/A
  Décimales: N/A
  Délai: 0 minutes
  Intervalle: 1440 minutes
  Nombre de barres: 446
  Période: 2024-06-05 00:00:00+00:00 à 2026-03-12 00:00:00+00:00

,CloseAsk,CloseBid,HighAsk,HighBid,LowAsk,LowBid,OpenAsk,OpenBid,Open,High,Low,Close
Time,,,,,,,,,,,,
2024-06-05 00:00:00+00:00,6.666,6.636,6.751,6.741,6.518,6.508,6.574,6.544,6.559,6.7460,6.5130,6.651
2024-06-06 00:00:00+00:00,6.685,6.655,6.687,6.657,6.523,6.513,6.666,6.636,6.651,6.6720,6.5180,6.670
2024-06-07 00:00:00+00:00,6.606,6.576,6.722,6.712,6.583,6.573,6.685,6.655,6.670,6.7170,6.5780,6.591
2024-06-10 00:00:00+00:00,6.738,6.708,6.770,6.740,6.457,6.427,6.606,6.576,6.591,6.7550,6.4420,6.723
2024-06-11 00:00:00+00:00,6.489,6.459,6.796,6.786,6.438,6.418,6.738,6.708,6.723,6.7910,6.4280,6.474
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-06 00:00:00+00:00,7.553,7.523,7.601,7.571,7.222,7.211,7.274,7.244,7.259,7.5860,7.2165,7.538
2026-03-09 00:00:00+00:00,7.769,7.739,7.965,7.935,7.371,7.361,7.553,7.523,7.538,7.9500,7.3660,7.754
2026-03-10 00:00:00+00:00,7.611,7.545,7.769,7.746,7.275,7.264,7.769,7.739,7.754,7.7575,7.2695,7.578
2026-03-11 00:00:00+00:00,7.949,7.919,7.973,7.943,7.529,7.499,7.611,7.545,7.578,7.9580,7.5140,7.934
2026-03-12 00:00:00+00:00,7.949,7.919,8.056,8.026,7.815,7.805,7.949,7.919,7.934,8.0410,7.8100,7.934

#### Getting  ID infos from `ISIN`

info_needed_for_trading()

donne le type et Uic (qui sont necessaire au trading)

In [14]:
info = client.info_needed_for_trading("CH1516774622")
print(info)

✅ Session toujours active.
{'uic': 54287165, 'type': 'MiniFuture'}

#### Getting Usefull detail about a Product

In [15]:
client.get_product_trading_details(info["uic"], info["type"])

✅ Session toujours active.
✅ Session toujours active.
✅ Session toujours active.
✓ LVMH Turbo Short 703.3319 Saxo: Bid: None, Ask: None

{'nom': 'LVMH Turbo Short 703.3319 Saxo',
 'sous_jacent': 'LVMH Moet Hennessy Louis Vuitton',
 'type_produit': 'MiniFuture',
 'direction': 'Short',
 'prix_unitaire': None,
 'devise': 'EUR',
 'barriere_desactivation': 703.33188,
 'distance_barriere_pct': 42.09,
 'ratio': 100.0,
 'uic_sous_jacent': 112813,
 'tick_size': 0.001,
 'statut': 'Tradable'}

#### Getting Full Detailed Infos From `UIC` and `AssetType`

In [16]:
details = client.get_product_full_details(info['uic'], info['type'])
details

✅ Session toujours active.

{'AffiliateInfoRequired': False,
 'AmountDecimals': 0,
 'AssetType': 'MiniFuture',
 'AverageVolume': 0.0,
 'BarrierDistance': 42.0872484848485,
 'CurrencyCode': 'EUR',
 'DefaultAmount': 1.0,
 'DefaultSlippage': 0.0,
 'DefaultSlippageType': 'Ticks',
 'Description': 'LVMH Turbo Short 703.3319 Saxo',
 'Exchange': {'CountryCode': 'DE',
  'ExchangeId': 'CATS_SAXO',
  'Name': 'CATS_SAXO',
  'TimeZoneId': '4'},
 'FinancingLevel': 740.349347,
 'Format': {'Decimals': 3, 'OrderDecimals': 3},
 'GroupId': 0,
 'IncrementSize': 1.0,
 'IsBarrierEqualsStrike': False,
 'IsComplex': True,
 'IsOcoOrderSupported': False,
 'IsPEAEligible': False,
 'IsPEASMEEligible': False,
 'IsRedemptionByAmounts': False,
 'IssueDate': '2025-12-22T00:00:00.000000Z',
 'IsSwitchBySameCurrency': False,
 'IsTradable': True,
 'LotSize': 1.0,
 'LotSizeType': 'NotUsed',
 'MinimumOrderValue': 0.0,
 'MinimumTradeSize': 1.0,
 'NonTradableReason': 'None',
 'OrderDistances': {'EntryDefaultDistance': 0.25,
  'EntryDefaultDistanceType': 'Percentage',
  'LimitDefaultDistance': 0.0,
  'LimitDefaultDistanceType': 'Percentage',
  'StopLimitDefaultDistance': 5.0,
  'StopLimitDefaultDistanceType': 'Pips',
  'StopLossDefaultDistance': 0.5,
  'StopLossDefaultDistanceType': 'Percentage',
  'StopLossDefaultEnabled': False,
  'StopLossDefaultOrderType': 'Stop',
  'TakeProfitDefaultDistance': 0.5,
  'TakeProfitDefaultDistanceType': 'Percentage',
  'TakeProfitDefaultEnabled': False},
 'PriceCurrency': 'EUR',
 'PriceToContractFactor': 1.0,
 'Ratio': 100.0,
 'SettlementStyle': 'CashDelivery',
 'StandardAmounts': [1.0,
  10.0,
  100.0,
  500.0,
  1000.0,
  10000.0,
  50000.0,
  100000.0],
 'StopLossLevel': 703.33188,
 'SupportedOrderTriggerPriceTypes': [],
 'SupportedOrderTypes': ['Market', 'Limit', 'StopIfTraded', 'StopLimit'],
 'Symbol': 'CH1516774622:cats',
 'TickSize': 0.001,
 'TradableAs': ['MiniFuture'],
 'TradableOn': ['78800/166433EUR'],
 'TradePerspective': 'Short',
 'TradingSignals': 'NotAllowed',
 'TradingStatus': 'Tradable',
 'Uic': 54287165,
 'UnderlyingAssetType': 'Stock',
 'UnderlyingDescription': 'LVMH Moet Hennessy Louis Vuitton',
 'UnderlyingTypeCategory': 'Instrument',
 'UnderlyingUic': 112813}

## Trading Function

#### Setting an Order (cannot have 2 Orders on the same asset)

In [19]:
#  Tentative d'ordre (le fix ManualOrder + Price est appliqué)
try:
    result = client.order(
        SellBuy="Buy",
        isLimit=True,
        Price=0.02, 
        productInfo=info,
        amount=2
    )
    print("Succès !", result)
except Exception as e:
    print("L'ordre a échoué.", e)

# IT CAN BE USEFULL TO CHECK YOUR ORDERS AFTERWARDS
# ordres_actifs = client.get_open_orders()
# print(f"Vous avez {len(ordres_actifs)} ordre(s) en cours.")

✅ Session toujours active.
Succès ! {'OrderId': '5382455434'}

In [22]:
info

{'uic': 42571691, 'type': 'MiniFuture'}

#### Cancel Order Methods

In [ ]:
# # 1. Identifier le produit
# # info = client.info_needed_for_trading("CH1351250548")
# uic = 42571691

# # 2. Nettoyer les anciens ordres de vente qui bloquent
# print("Nettoyage des anciens ordres...")
# client.cancel_all_orders_for_uic(uic)


# # 4. Vérifier la liste finale
# # print("Ordres actifs :", client.get_open_orders())

Nettoyage des anciens ordres...
✅ Session toujours active.
✅ Session toujours active.
✅ Session toujours active.

TypeError: string indices must be integers, not 'str'

In [27]:
client.cancel_order(5382455430)

✅ Session toujours active.
❌ Erreur lors de l'annulation : {"Orders":[{"OrderId":"5382455430"}]}

False