In [93]:
import importlib, Saxo
importlib.reload(Saxo)
from Saxo import SaxoClient
import Key as Key


client = SaxoClient(
    app_key=Key.app_key,
    app_secret=Key.app_secret,
    app_name=Key.app_name,
    redirect_uri=Key.redirect_uri
)

# Remplace ton ancien login par celui-ci :
client.smart_login()

# Ton code de trading continue ici...
print(f"Solde cash : {client.get_cash()}")

📂 Jetons chargés depuis le fichier.
🔑 Token chargé et session prête.
✅ Session toujours active.
Solde cash : 125.05

## GETTING ACCOUNT DATA

#### Getting the total valuation of portefolio (Cash + Invested position) #notworking

In [6]:
Total= client.get_total()
Total

117.59

#### Getting cash

returning cash amount

In [5]:
cash=client.get_cash()
cash

125.05

#### Getting account Metadata

In [46]:
accounts = client.get_accounts()
for a in accounts:
    print(a["AccountKey"]+"\n",
           a["AccountType"]+"\n",
             a["Currency"]+"\n",
               a["AccountId"]+"\n")

r5JIKMkqsHq5a-PpeifkDw==
 Normal
 EUR
 78800/166433EUR

#### Getting positions

In [7]:
res = client.get_positions()
for p in res["positions"]:
    print(p)

#### Getting Order list

In [28]:
ordres_actifs = client.get_open_orders()
print(f"Vous avez {len(ordres_actifs)} ordre(s) en cours.")

Vous avez 0 ordre(s) en cours.

#### Getting transaction Histo

In [95]:
# 30 dernières exécutions sur ce produit (fenêtre héritée de get_last_transactions si fournie)
df = client.get_last_trades(n=30, uic=42571691)
df

,TradeTimestamp,ValueDate,BuySell,ToOpenOrClose,Price,Quantity,BookedAmount,Currency,Uic,TradeId,Description
0,2026-02-27 12:18:34.550000+00:00,2026-03-03,Sell,ToOpen,7.46,-1.0,7.46,EUR,42571691,6607939567,TotalEnergies Turbo Long 31.9039 Saxo
1,2026-02-25 12:49:12.067000+00:00,2026-02-27,Buy,ToOpen,7.44,1.0,-7.44,EUR,42571691,6604194576,TotalEnergies Turbo Long 31.9039 Saxo

## GET PRODUCT DATA

#### Historical data (Notworking ATM)

In [9]:
# df=client.get_historical_data(42571691, "MiniFuture", horizon=1440, count=200, mode=None, time=None)
# df

#### Getting Current price data (Notworking ATM)

In [10]:
client.diagnostic_turbo(55005069)

--- DIAGNOSTIC UIC 55005069 ---
PriceTypeAsk: NoAccess
ErrorCode: None
PriceSource: PAR_ACCESS

{'AssetType': 'WarrantKnockOut',
 'LastUpdated': '0001-01-01T00:00:00.000000Z',
 'PriceSource': 'PAR_ACCESS',
 'Quote': {'Amount': 0,
  'AskSize': 0.0,
  'BidSize': 0.0,
  'ErrorCode': 'None',
  'PriceSource': 'PAR_ACCESS',
  'PriceSourceType': 'Firm',
  'PriceTypeAsk': 'NoAccess',
  'PriceTypeBid': 'NoAccess'},
 'Uic': 55005069}

#### Getting current price

In [11]:
info = client.info_needed_for_trading("CH1351250548")
# client.get_market_price(info["uic"], info["type"])
client.get_price_forced(info["uic"], info["type"])

{'Instrument': 'TotalEnergies Turbo Long 31.9039 Saxo',
 'Dernier_Cours': None,
 'Achat_Bid': None,
 'Vente_Ask': None,
 'Clôture_Précédente': 7.391,
 'Statut_Prix': None,
 'Devise': 'EUR',
 'Message': 'Marché fermé ou flux restreint'}

#### Get Hisorical prices

get_chart_data(`uic`,`asset_type`,`horizon`,`count`,`mode`,`time`)


 - Universal Instrument Code (ex: 21 pour EUR/USD)
 - asset_type (str): Type d'actif (FxSpot, Stock, etc.)
 - horizon (int): Intervalle en minutes (1, 5, 15, 60, 1440=daily, etc.)
 - count (int): Nombre de barres à récupérer (max 1200)
 - mode (str): 'From' ou 'UpTo' - si spécifié, time doit aussi être spécifié
 - time (str): Date/heure ISO format (ex: '2026-02-13T00:00:00Z')

return un df

In [20]:

info = client.info_needed_for_trading("CH1351250548")


df=client.get_chart_data(info["uic"], info["type"], horizon=1440, count=1200, mode=None, time=None)
df

✓ Données récupérées pour Instrument
  Description: N/A
  Devise: N/A
  Décimales: N/A
  Délai: 0 minutes
  Intervalle: 1440 minutes
  Nombre de barres: 437
  Période: 2024-06-05 00:00:00+00:00 à 2026-02-27 00:00:00+00:00

,CloseAsk,CloseBid,HighAsk,HighBid,LowAsk,LowBid,OpenAsk,OpenBid,Open,High,Low,Close
Time,,,,,,,,,,,,
2024-06-05 00:00:00+00:00,6.666,6.636,6.751,6.741,6.518,6.508,6.574,6.544,6.559,6.746,6.5130,6.651
2024-06-06 00:00:00+00:00,6.685,6.655,6.687,6.657,6.523,6.513,6.666,6.636,6.651,6.672,6.5180,6.670
2024-06-07 00:00:00+00:00,6.606,6.576,6.722,6.712,6.583,6.573,6.685,6.655,6.670,6.717,6.5780,6.591
2024-06-10 00:00:00+00:00,6.738,6.708,6.770,6.740,6.457,6.427,6.606,6.576,6.591,6.755,6.4420,6.723
2024-06-11 00:00:00+00:00,6.489,6.459,6.796,6.786,6.438,6.418,6.738,6.708,6.723,6.791,6.4280,6.474
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-02-23 00:00:00+00:00,7.210,7.180,7.275,7.265,6.862,6.832,7.115,7.085,7.100,7.270,6.8470,7.195
2026-02-24 00:00:00+00:00,7.306,7.276,7.345,7.335,7.173,7.162,7.210,7.180,7.195,7.340,7.1675,7.291
2026-02-25 00:00:00+00:00,7.413,7.383,7.509,7.499,7.303,7.273,7.306,7.276,7.291,7.504,7.2880,7.398
2026-02-26 00:00:00+00:00,7.401,7.381,7.510,7.500,7.258,7.248,7.413,7.383,7.398,7.505,7.2530,7.391
2026-02-27 00:00:00+00:00,7.401,7.381,7.489,7.479,7.283,7.253,7.401,7.381,7.391,7.484,7.2680,7.391

In [ ]:
# # prix_lvmh = client.get_product_current_prices(112813, 'CfdOnStock')
# prix_lvmh = client.get_product_current_prices(55005069, 'WarrantKnockOut')
# prix_lvmh

{'Dernier_Prix': None,
 'Achat_Bid': None,
 'Vente_Ask': None,
 'Cloture_Precedente': None,
 'Statut_Flux': 'DIFFÉRÉ/NO_ACCESS',
 'Instrument': 'Danone Turbo BEST Put 75 20Mar26 SOG',
 'Message': '⚠️ Activez le flux Euronext dans SaxoTrader pour voir le Bid/Ask'}

#### Getting  ID infos from `ISIN`

In [24]:
info = client.info_needed_for_trading("CH1351250548")
print(info)

{'uic': 42571691, 'type': 'MiniFuture'}

#### Getting Usefull detail about a Product

In [86]:
client.get_product_trading_details(info["uic"], info["type"])

✓ TotalEnergies Turbo Long 31.9039 Saxo: Bid: None, Ask: None

{'nom': 'TotalEnergies Turbo Long 31.9039 Saxo',
 'sous_jacent': 'TotalEnergies SE',
 'type_produit': 'MiniFuture',
 'direction': 'Long',
 'prix_unitaire': None,
 'devise': 'EUR',
 'barriere_desactivation': 31.903903,
 'distance_barriere_pct': 52.58,
 'ratio': 5.0,
 'uic_sous_jacent': 23255427,
 'tick_size': 0.001,
 'statut': 'Tradable'}

#### Getting Full Detailed Infos From `UIC` and `AssetType`

In [ ]:
details = client.get_product_full_details(info['uic'], info['type'])
details

{'AffiliateInfoRequired': False,
 'AmountDecimals': 0,
 'AssetType': 'MiniFuture',
 'AverageVolume': 1.0,
 'BarrierDistance': 52.5804057669441,
 'CurrencyCode': 'EUR',
 'DefaultAmount': 1.0,
 'DefaultSlippage': 0.0,
 'DefaultSlippageType': 'Ticks',
 'Description': 'TotalEnergies Turbo Long 31.9039 Saxo',
 'Exchange': {'CountryCode': 'DE',
  'ExchangeId': 'CATS_SAXO',
  'Name': 'CATS_SAXO',
  'TimeZoneId': '4'},
 'FinancingLevel': 30.384669,
 'Format': {'Decimals': 3, 'OrderDecimals': 3},
 'GroupId': 0,
 'IncrementSize': 1.0,
 'IsBarrierEqualsStrike': False,
 'IsComplex': True,
 'IsOcoOrderSupported': False,
 'IsPEAEligible': False,
 'IsPEASMEEligible': False,
 'IsRedemptionByAmounts': False,
 'IssueDate': '2024-06-05T00:00:00.000000Z',
 'IsSwitchBySameCurrency': False,
 'IsTradable': True,
 'LotSize': 1.0,
 'LotSizeType': 'NotUsed',
 'MinimumOrderValue': 0.0,
 'MinimumTradeSize': 1.0,
 'NonTradableReason': 'None',
 'OrderDistances': {'EntryDefaultDistance': 0.25,
  'EntryDefaultDistanceType': 'Percentage',
  'LimitDefaultDistance': 0.0,
  'LimitDefaultDistanceType': 'Percentage',
  'StopLimitDefaultDistance': 5.0,
  'StopLimitDefaultDistanceType': 'Pips',
  'StopLossDefaultDistance': 0.5,
  'StopLossDefaultDistanceType': 'Percentage',
  'StopLossDefaultEnabled': False,
  'StopLossDefaultOrderType': 'Stop',
  'TakeProfitDefaultDistance': 0.5,
  'TakeProfitDefaultDistanceType': 'Percentage',
  'TakeProfitDefaultEnabled': False},
 'PriceCurrency': 'EUR',
 'PriceToContractFactor': 1.0,
 'Ratio': 5.0,
 'SettlementStyle': 'CashDelivery',
 'StandardAmounts': [1.0,
  10.0,
  100.0,
  500.0,
  1000.0,
  10000.0,
  50000.0,
  100000.0],
 'StopLossLevel': 31.903903,
 'SupportedOrderTriggerPriceTypes': [],
 'SupportedOrderTypes': ['Market', 'Limit', 'StopIfTraded', 'StopLimit'],
 'Symbol': 'CH1351250548:cats',
 'TickSize': 0.001,
 'TradableAs': ['MiniFuture'],
 'TradableOn': ['78800/166433EUR'],
 'TradePerspective': 'Long',
 'TradingSignals': 'NotAllowed',
 'TradingStatus': 'Tradable',
 'Uic': 42571691,
 'UnderlyingAssetType': 'Stock',
 'UnderlyingDescription': 'TotalEnergies SE',
 'UnderlyingTypeCategory': 'Instrument',
 'UnderlyingUic': 23255427}

## Trading Function

#### Setting an Order (cannot have 2 Orders on the same asset)

In [97]:
#  Tentative d'ordre (le fix ManualOrder + Price est appliqué)
try:
    result = client.order(
        SellBuy="Sell",
        isLimit=True,
        Price=7.52, 
        productInfo=info,
        amount=1
    )
    print("Succès !", result)
except Exception as e:
    print("L'ordre a échoué.", e)

# IT CAN BE USEFULL TO CHECK YOUR ORDERS AFTERWARDS
# ordres_actifs = client.get_open_orders()
# print(f"Vous avez {len(ordres_actifs)} ordre(s) en cours.")

Succès ! {'OrderId': '5376481177'}

#### Cancel Order Methods

In [55]:
# 1. Identifier le produit
info = client.info_needed_for_trading("CH1351250548")
uic = info['uic']

# 2. Nettoyer les anciens ordres de vente qui bloquent
print("Nettoyage des anciens ordres...")
client.cancel_all_orders_for_uic(uic)


# 4. Vérifier la liste finale
# print("Ordres actifs :", client.get_open_orders())

Nettoyage des anciens ordres...
❌ Erreur lors de l'annulation : {"Orders":[{"OrderId":"5376365080"}]}

0

In [ ]:
# client.cancel_order(5376370437)

❌ Erreur lors de l'annulation : {"Orders":[{"OrderId":"5376370437"}]}

False